package actions

import (
<<<<<<< HEAD
	"fmt"

	"github.com/MakeNowJust/heredoc"
	"github.com/cli/cli/pkg/cmdutil"
	"github.com/cli/cli/pkg/iostreams"
	"github.com/spf13/cobra"
)

type ActionsOptions struct {
	IO *iostreams.IOStreams
}

func NewCmdActions(f *cmdutil.Factory) *cobra.Command {
	opts := ActionsOptions{
		IO: f.IOStreams,
	}

	cmd := &cobra.Command{
		Use:    "actions",
		Short:  "Learn about working with GitHub actions",
		Args:   cobra.ExactArgs(0),
		Hidden: true,
		Run: func(cmd *cobra.Command, args []string) {
			actionsRun(opts)
		},
	}

	return cmd
}

func actionsRun(opts ActionsOptions) {
	cs := opts.IO.ColorScheme()
	fmt.Fprint(opts.IO.Out, heredoc.Docf(`
			Welcome to GitHub Actions on the command line.

			This part of gh is in beta and subject to change!

			To follow along while we get to GA, please see this
			tracking issue: https://github.com/cli/cli/issues/2889

			%s
			gh run list:    List recent workflow runs
			gh run view:    View details for a given workflow run

			%s
			gh job view:   View details for a given job
		`,
		cs.Bold("Working with runs"),
		cs.Bold("Working with jobs within runs")))
	/*
		fmt.Fprint(opts.IO.Out, heredoc.Docf(`
			Welcome to GitHub Actions on the command line.

			%s
			gh workflow list:    List workflows in the current repository
			gh workflow run:     Kick off a workflow run
			gh workflow init:    Create a new workflow
			gh workflow check:   Check a workflow file for correctness

			%s
			gh run list:    List recent workflow runs
			gh run view:    View details for a given workflow run
			gh run watch:   Watch a streaming log for a workflow run

			%s
			gh job view:   View details for a given job
			gh job run:    Run a given job within a workflow
		`,
			cs.Bold("Working with workflows"),
			cs.Bold("Working with runs"),
			cs.Bold("Working with jobs within runs")))
	*/
=======
	"github.com/MakeNowJust/heredoc"
	"github.com/cli/cli/v2/pkg/cmdutil"
	"github.com/cli/cli/v2/pkg/iostreams"
	"github.com/spf13/cobra"
)

func NewCmdActions(f *cmdutil.Factory) *cobra.Command {
	cs := f.IOStreams.ColorScheme()

	cmd := &cobra.Command{
		Use:    "actions",
		Short:  "Learn about working with GitHub Actions",
		Long:   actionsExplainer(cs),
		Hidden: true,
	}

	cmdutil.DisableAuthCheck(cmd)

	return cmd
}

func actionsExplainer(cs *iostreams.ColorScheme) string {
	header := cs.Bold("Welcome to GitHub Actions on the command line.")
	runHeader := cs.Bold("Interacting with workflow runs")
	workflowHeader := cs.Bold("Interacting with workflow files")
	cacheHeader := cs.Bold("Interacting with the GitHub Actions cache")

	return heredoc.Docf(`
			%[2]s

			GitHub CLI integrates with GitHub Actions to help you manage runs and workflows.

			%[3]s
			gh run list:      List recent workflow runs
			gh run view:      View details for a workflow run or one of its jobs
			gh run watch:     Watch a workflow run while it executes
			gh run rerun:     Rerun a failed workflow run
			gh run download:  Download artifacts generated by runs

			To see more help, run %[1]sgh help run <subcommand>%[1]s

			%[4]s
			gh workflow list:     List workflow files in your repository
			gh workflow view:     View details for a workflow file
			gh workflow enable:   Enable a workflow file
			gh workflow disable:  Disable a workflow file
			gh workflow run:      Trigger a workflow_dispatch run for a workflow file

			To see more help, run %[1]sgh help workflow <subcommand>%[1]s

			%[5]s
			gh cache list:    List all the caches saved in GitHub Actions for a repository
			gh cache delete:  Delete one or all saved caches in GitHub Actions for a repository

			To see more help, run %[1]sgh help cache <subcommand>%[1]s

		`, "`", header, runHeader, workflowHeader, cacheHeader)
>>>>>>> origin/trunk
}
